from questions import Question, QuestionSet
from random import randint, choice, randrange
from definitions.common import randdecimal, male_names, female_names, numbers, weekdays, measurement_units

winkel_berechnen_1 = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Winkel in Dreiecken',
    title='Winkel berechnen (1)',
    instruction='Berechne den fehlenden Winkel',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>γ = 180° - ( ___° + ___° )</mat><br>'
                    '<mat>γ = 180° - ___°</mat><br>'
                    '<mat>γ = ___°</mat>',
            correct='{{v1}};{{v2}};{{v1+v2}};{{180-v1-v2}}',
            variables={
                'v1': (randrange, 85, 115, 5),
                'v2': (randrange, 35, 50, 5),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(0, 2), (4, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 2),
                     'p1': (5, 0),
                     'p2': (4, 3),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (4, 3),
                     'p1': (0, 2),
                     'p2': (5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (5, 0),
                     'p1': (4, 3),
                     'p2': (0, 2),
                     'text': '{{v2}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
            },
        ),
        Question(
            formula='<mat>α = 180° - ( ___° + ___° )</mat><br>'
                    '<mat>α = 180° - ___°</mat><br>'
                    '<mat>α = ___°</mat>',
            correct='{{v1}};{{v1}};{{v1*2}};{{180-v1*2}}',
            variables={
                'v1': (randint, 70, 80),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(0, 2), (5, 4), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 2),
                     'p1': (5, 0),
                     'p2': (5, 4),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 4),
                     'p1': (0, 2),
                     'p2': (5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (5, 0),
                     'p1': (5, 4),
                     'p2': (0, 2),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
            },
        ),
        Question(
            formula='<mat>β = 180° - ( ___° + ___° )</mat><br>'
                    '<mat>β = 180° - ___°</mat><br>'
                    '<mat>β = ___°</mat>',
            correct='{{v1}};{{v1}};{{v1*2}};{{180-v1*2}}',
            variables={
                'v1': 60,
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(0, 0), (2.5, '{{2.5*(3**0.5)}}'), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (2.5, '{{2.5*(3**0.5)}}'),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (2.5, '{{2.5*(3**0.5)}}'),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (5, 0),
                     'p1': (2.5, '{{2.5*(3**0.5)}}'),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                ],
            },
        )
    ]
)

winkel_berechnen_2 = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Winkel in Dreiecken',
    title='Winkel berechnen (2)',
    instruction='Berechne die Innenwinkel des Dreiecks',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>α = ___°</mat> <br> '
                    '<mat>γ = ___°</mat> <br>'
                    '<mat>β = ___°</mat>',
            correct='{{v2}};{{180-v1}};{{180-v2-(180-v1)}}',
            variables={
                'v1': (randrange, 95, 125, 5),
                'v2': (randrange, 35, 50, 5),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'b',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 1),
                     'p2': (5, 1),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (4, 4),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'a',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                     }},
                     ],
                'angles': [
                    {'xy': (1.25, 1),
                     'p1': (5, 1),
                     'p2': (5, 4),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (1.25, 1),
                     'p1': (0, 1),
                     'p2': (0, 0),
                     'text': '{{v2}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': ('{{25/6}}', '{{20/6}}'),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': ('{{25/6}}', '{{20/6}}'),
                     'p1': (5, 0),
                     'p2': (5, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (4.75, 1),
                     'p1': (4, 4),
                     'p2': (0, 1),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                ],
            },
        ),
        Question(
            formula='<mat>α = ___°</mat> <br> '
                    '<mat>γ = ___°</mat> <br>'
                    '<mat>β = ___°</mat>',
            correct='{{180-v2}};{{v2}};{{180-v1-(180-v2)}}',
            variables={
                'v1': (randint, 95, 125),
                'v2': (randint, 50, 60),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'b ',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (1, 4),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': ' a',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                    {'p1': (2, 0),
                     'p2': (2.6, 2.4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': ' k',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     }
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (1, 4),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (1, 4),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (1, 4),
                     'p2': (0, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2, 0),
                     'p1': (2.6, 2.4),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (2.6, 2.4),
                     'p1': (2, 0),
                     'p2': (5, 0),
                     'text': '{{v2}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
                'texts': [
                    {'x': 4,
                     'y': 3,
                     's': 'b | k',
                     'fontsize': 'large',
                     'ha': 'right',
                     },
                ]
            },
        ),
        Question(
            formula='<mat>α = ___°</mat> <br> '
                    '<mat>γ = ___°</mat> <br>'
                    '<mat>β = ___°</mat>',
            correct='{{90-v2}};90;{{v2}}',
            variables={
                'v2': (randint, 50, 60),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (3.75, 3),
                     'linewidth': 0,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'b ',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (5, 0.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (1.8, 4),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.6, 3),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'color': 'black',
                     'zorder': 3,
                     'text': ' a',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                    {'p1': (0, '{{100/41}}'),
                     'p2': (5, '{{100/41}}'),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, '{{100/41}}'),
                     'p2': (2, '{{100/41}}'),
                     'linewidth': 0,
                     'text': 'g',
                     'text_kw': {
                         'xytext': (0, 4),
                         'textcoords': 'offset points',
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }
                     },
                ],
                'angles': [
                    {'xy': (0.625, 0.5),
                     'p1': (5, 0.5),
                     'p2': (5, 4),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (4.6, 0.5),
                     'p1': (1.8, 4),
                     'p2': (0, 0.5),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': ('{{125/41}}', '{{100/41}}'),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': ('{{125/41}}', '{{100/41}}'),
                     'p1': (5, 4),
                     'p2': (1.8, 4),
                     'text': '•',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': ('{{125/41}}', '{{100/41}}'),
                     'p1': (5, 0),
                     'p2': (5, '{{100/41}}'),
                     'text': '{{v2}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
                'texts': [
                    {'x': 0.5,
                     'y': 3.5,
                     's': 'c | g',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'top',
                     },
                ]
            },
        ),
        Question(
            formula='<mat>α = ___°</mat> <br> '
                    '<mat>γ = ___°</mat> <br>'
                    '<mat>β = ___°</mat>',
            correct='{{v1-90}};{{v2+90}};{{180-v1-v2}}',
            variables={
                'v1': (randint, 110, 120),
                'v2': (randint, 35, 45),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0.5, 0),
                     'p2': (4.5, 3),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.5, 0),
                     'p2': (4.5, 3),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4.5, 0),
                     'p2': (4.5, 4),
                     'linewidth': 2,
                     'linestyle': 'dashed',
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0.5, 0),
                     'p1': (5, 0),
                     'p2': (4.5, 3),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2.5, 0),
                     'p1': (4.5, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (4.5, 3),
                     'p1': (0.5, 0),
                     'p2': (2.5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (4.5, 0),
                     'p1': (4.5, 4),
                     'p2': (0, 0),
                     'text': '•',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (4.5, 3),
                     'p1': (4.5, 4),
                     'p2': (0.5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (4.5, 3),
                     'p1': (2.5, 0),
                     'p2': (4.5, 0),
                     'text': '{{v2}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
            },
        ),
    ]
)

satz_des_thales_anwenden = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Winkel in Dreiecken',
    title='Satz des Thales anwenden',
    instruction='Berechne die gesuchten Winkel',
    question_type='gap',
    questions=[
        Question(
            hint='Beachte, dass das Dreieck ∆AMC gleichschenklig ist. '
                 'Daher sind in diesem Dreieck die Winkel an A und C gleichgroß. '
                 'Da auch das Dreieck ∆MBC gleichschenklig ist, '
                 'sind in diesem Dreieck die Winkel an B und C gleichgroß.',
            formula='<mat>α = ___°</mat> <br> '
                    '<mat>β = ___°</mat> <br>'
                    '<mat>γ = ___°</mat>',
            correct='{{(90-v1/2)|round|int}};{{(v1/2)|round|int}};90',
            variables={
                'v1': (randrange, 94, 116, 2),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (2.9341, 2.46),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.9341, 2.46),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.5, 0),
                     'p2': (2.9341, 2.46),
                     'linewidth': 2,
                     'linestyle': 'dashed',
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (2.5, 0),
                     'p1': (5, 0),
                     'p2': (0, 0),
                     'size': 5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (2.9341, 2.46),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2.9341, 2.46),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': '  γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (2.9341, 2.46),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2.5, 0),
                     'p1': (2.9341, 2.46),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
                'texts': [
                    {'x': 0,
                     'y': 0,
                     's': 'A',
                     'fontsize': 'large',
                     'ha': 'right',
                     'va': 'top',
                     },
                    {'x': 2.9341,
                     'y': 2.46,
                     's': 'C',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'left',
                     },
                    {'x': 2.5,
                     'y': 0,
                     's': 'M',
                     'fontsize': 'large',
                     'va': 'top',
                     },
                    {'x': 5,
                     'y': 0,
                     's': 'B',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'left',
                     },
                ]
            },
        ),
        Question(
            hint='Beachte, dass das Dreieck ∆AMC gleichschenklig ist. '
                 'Daher sind in diesem Dreieck die Winkel an A und C gleichgroß. '
                 'Da auch das Dreieck ∆MBC gleichschenklig ist, '
                 'sind in diesem Dreieck die Winkel an B und C gleichgroß.',
            formula="<mat> α = ___°<br>"
                    "β = ___°<br>"
                    "γ = ___°<br>"
                    "δ = δ' = ___°<br>"
                    "ε = ___°</mat>",
            correct='{{v1}};{{90-v1}};{{90-v1}};{{v1*2}};{{90-v1*2}}',
            variables={
                'v1': (randint, 68, 78),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '-1.25',
                                'ymax': '2.5'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (0.235, 1.055),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0.235, 1.055),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0.235, 1.055),
                     'p2': (2.5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.5, 0),
                     'p2': (4.5525, -0.9575),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4.5525, -0.9575),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (3.75, 0.02),
                     'p2': (3.75, -0.02),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (2.5, 0),
                     'p1': (5, 0),
                     'p2': (0, 0),
                     'size': 5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (3.75, 0),
                     'p1': (2.5, 0),
                     'p2': (5, 0),
                     'size': 2.5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (0, 0),
                     'p1': (2.5, 0),
                     'p2': (0.235, 1.055),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (0.235, 1.055),
                     'p1': (0, 0),
                     'p2': (2.5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (0.235, 1.055),
                     'p1': (2.5, 0),
                     'p2': (5, 0),
                     'text': '    γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 2,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2.5, 0),
                     'p1': (0.235, 1.055),
                     'p2': (0, 0),
                     'text': 'δ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (2.5, 0),
                     'p1': (4.5525, -0.9575),
                     'p2': (5, 0),
                     'text': "δ'",
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (0.235, 1.055),
                     'p2': (2.5, 0),
                     'text': 'β    ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 2,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (4.5525, -0.9575),
                     'p1': (5, 0),
                     'p2': (2.5, 0),
                     'text': '•',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (5, 0),
                     'p1': (2.5, 0),
                     'p2': (4.5525, -0.9575),
                     'text': 'ε',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                ],
                'texts': [
                    {'x': 0,
                     'y': 0,
                     's': 'A',
                     'fontsize': 'large',
                     'ha': 'right',
                     'va': 'top',
                     },
                    {'x': 0.235,
                     'y': 1.055,
                     's': 'C',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'right',
                     },
                    {'x': 2.5,
                     'y': 0,
                     's': 'M ',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'right',
                     },
                    {'x': 5,
                     'y': 0,
                     's': 'B',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'left',
                     },
                    {'x': 4.5525,
                     'y': -0.9575,
                     's': 'D',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'left',
                     },
                ]
            },
        ),
        Question(
            hint='Beachte, dass das Dreieck ∆ABD nach dem Satz des Thales an D rechtwinklig ist. '
                 'Nach dem Nebenwinkelsatz ist auch das Dreieck ∆BCD an D rechtwinklig.',
            formula='<mat>α = ___°<br>'
                    'β_1 = ___°<br>'
                    'β_2 = ___°</mat>',
            correct='{{((180-v1)/2)|round|int}};{{(v1/2)|round|int}};{{90-v1}}',
            variables={
                'v1': (randrange, 70, 80, 2),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (2.0659, 2.46),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.0659, 2.46),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.0659, 2.46),
                     'p2': (3, 3.57),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (3, 3.57),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (2.5, 0),
                     'p1': (5, 0),
                     'p2': (0, 0),
                     'size': 5,
                     'zorder': 2,
                     'color': 'black',
                     },
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (2.0659, 2.46),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (2.0659, 2.46),
                     'p2': (0, 0),
                     'text': 'β₁',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (3, 3.57),
                     'p2': (2.0659, 2.46),
                     'text': 'β₂',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 2.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (3, 3.57),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'black',
                     },
                ],
                'texts': [
                    {'x': 0,
                     'y': 0,
                     's': 'A',
                     'fontsize': 'large',
                     'ha': 'right',
                     'va': 'top',
                     },
                    {'x': 2.0659,
                     'y': 2.46,
                     's': 'D',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'right',
                     },
                    {'x': 3,
                     'y': 3.57,
                     's': 'C',
                     'fontsize': 'large',
                     'va': 'bottom',
                     },
                    {'x': 2.5,
                     'y': 0,
                     's': 'M',
                     'fontsize': 'large',
                     'va': 'top',
                     },
                    {'x': 5,
                     'y': 0,
                     's': 'B',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'left',
                     },
                    {'x': 0,
                     'y': 2.5,
                     's': 'CA = BC',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'left',
                     },
                ]
            },
        ),
    ]
)

winkel_beschriebener_dreiecke_berechnen = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Winkel in Dreiecken',
    title='Winkel beschriebener Dreiecke berechnen',
    instruction='Berechne die fehlenden Winkel',
    question_type='gap',
    questions=[
        Question(
            formula='α ist mit {{v1*2}}° doppelt so groß wie β. <br><br>'
                    'α = {{v1*2}}° <br> β = ___° <br> γ = ___°',
            correct='{{v1}};{{180-v1*3}}',
            variables={
                'v1': (randrange, 20, 55, 5),
            },
        ),
        Question(
            formula='α ist rechtwinklig. γ ist doppelt so groß wie β.<br><br>'
                    'α = ___° <br> β = ___° <br> γ = ___°',
            correct='90;30;60',
            variables={},
        ),
        Question(
            formula='α ist {{v1}}° groß. β ist {{v1-v2}}° kleiner als α. <br><br>'
                    'α = {{v1}}° <br> β = ___° <br> γ = ___',
            correct='{{v1}};{{v2}};{{180-v1-v2}}',
            variables={
                'v1': (randrange, 85, 130, 5),
                'v2': (randrange, 25, 50),
            },
        ),
        ]
)

kongruenzsatze_anwenden_1 = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Kongruenz und Kongruenzsätze',
    title='Kongruenzsätze anwenden (1)',
    instruction='',
    question_type='MC',
    questions=[
        Question(
            formula='Sind die Dreiecke kongruent zueinander?',
            correct='kongruent',
            wrong_1='nicht kongruent',
            wrong_2='nicht genug Vorgaben',
            variables={
                'v1': (randint, 80, 100),
                'v2': (randint, 5, 9),
                'v3': (randrange, 10, 13),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (5, 3.5),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                ],
                'angles': [
                    {'xy': (0, 0.5),
                     'p1': (3, 0),
                     'p2': (1, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 3.5),
                     'p1': (2, 4),
                     'p2': (4, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Mit welchem Kongruenzsatz kann die Kongruenz nachgewiesen werden?',
            correct='Ssw',
            wrong_1='sss',
            wrong_2='sws',
            wrong_3='wsw',
            hint='Zwei Seiten und der Winkel, der der längeren Seite gegenüberliegt, stimmen überein. '
                 'Daher sind die Dreiecke nach dem Kongruenzsatz „Ssw“ kongruent zueinander',
            variables={
                'v1': (randint, 80, 100),
                'v2': (randint, 5, 9),
                'v3': (randrange, 10, 13),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (5, 3.5),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                ],
                'angles': [
                    {'xy': (0, 0.5),
                     'p1': (3, 0),
                     'p2': (1, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 3.5),
                     'p1': (2, 4),
                     'p2': (4, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Sind die Dreiecke kongruent zueinander?',
            correct='kongruent',
            wrong_1='nicht kongruent',
            wrong_2='nicht genug Vorgaben',
            hint='Da zwei Winkel der Dreiecke gleichgroß sind, müssen die dritten Winkel auch gleich groß sein.',
            variables={
                'v1': (randint, 80, 100),
                'v2': (randint, 5, 15),
                'v3': (randint, 40, 50),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (5, 3.5),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0.5),
                     'p1': (3, 0),
                     'p2': (1, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (1, 4),
                     'p1': (0, 0.5),
                     'p2': (3, 0),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 3.5),
                     'p1': (2, 4),
                     'p2': (4, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (4, 0),
                     'p1': (5, 3.5),
                     'p2': (2, 4),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Mit welchem Kongruenzsatz kann die Kongruenz nachgewiesen werden?',
            correct='wsw',
            wrong_1='sss',
            wrong_2='sws',
            wrong_3='Ssw',
            hint='Da eine Seite und zwei Winkel übereinstimmen, '
                 'sind die Dreiecke nach dem Kongruenzsatz „wow“ kongruent zueinander.',
            variables={
                'v1': (randint, 80, 100),
                'v2': (randint, 5, 15),
                'v3': (randint, 40, 50),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                    {'p1': (5, 3.5),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0.5),
                     'p1': (3, 0),
                     'p2': (1, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (1, 4),
                     'p1': (0, 0.5),
                     'p2': (3, 0),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 3.5),
                     'p1': (2, 4),
                     'p2': (4, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (4, 0),
                     'p1': (5, 3.5),
                     'p2': (2, 4),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Sind die Dreiecke kongruent zueinander?',
            correct='nicht genug Vorgaben',
            wrong_1='nicht kongruent',
            wrong_2='kongruent',
            hint='Dreiecke, die in den Winkelgrößen übereinstimmen, müssen nicht kongruent zueinander sein, '
                 'da die Seitenlängen der Dreiecke sich dennoch unterscheiden können. '
                 'Anhand der Vorgaben des Bildes kann dies aber nicht eindeutig beurteilt werden.',
            variables={
                'v1': (randint, 80, 100),
                'v3': (randint, 40, 50),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (5, 3.5),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0.5),
                     'p1': (3, 0),
                     'p2': (1, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (1, 4),
                     'p1': (0, 0.5),
                     'p2': (3, 0),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (3, 0),
                     'p1': (1, 4),
                     'p2': (0, 0.5),
                     'text': '{{180-v1-v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 3.5),
                     'p1': (2, 4),
                     'p2': (4, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (2, 4),
                     'p1': (4, 0),
                     'p2': (5, 3.5),
                     'text': '{{180-v1-v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (4, 0),
                     'p1': (5, 3.5),
                     'p2': (2, 4),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Sind die Dreiecke kongruent zueinander?',
            correct='kongruent',
            wrong_1='nicht kongruent',
            wrong_2='nicht genug Vorgaben',
            variables={
                'v1': (randint, 40, 50),
                'v2': (randint, 5, 9),
                'v3': (randint, 10, 13),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4, 0),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }
                     },
                ],
                'angles': [
                    {'xy': (1, 4),
                     'p1': (0, 0.5),
                     'p2': (3, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (4, 0),
                     'p1': (5, 3.5),
                     'p2': (2, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Mit welchem Kongruenzsatz kann die Kongruenz nachgewiesen werden?',
            correct='sws',
            wrong_1='wow',
            wrong_2='sws',
            wrong_3='Ssw',
            hint='Da zwei Seiten und der davon eingeschlossene Winkel übereinstimmen, '
                 'sind die Dreiecke nach dem Kongruenzsatz „sws" kongruent zueinander.',
            variables={
                'v1': (randint, 40, 50),
                'v2': (randint, 5, 9),
                'v3': (randint, 10, 13),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0.5),
                     'p2': (1, 4),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (1, 4),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4, 0),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }
                     },
                ],
                'angles': [
                    {'xy': (1, 4),
                     'p1': (0, 0.5),
                     'p2': (3, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (4, 0),
                     'p1': (5, 3.5),
                     'p2': (2, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Sind die Dreiecke kongruent zueinander?',
            correct='nicht kongruent',
            wrong_1='nicht genug Vorgaben',
            wrong_2='kongruent',
            hint='Die Dreiecke sind nicht kongruent zueinander, da nicht alle Seiten gleich lang sind.',
            variables={
                'v1': (randint, 7, 11),
                'v2': (randint, 5, 9),
                'v3': (randint, 10, 13),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     }
                     },
                    {'p1': (0, 0.5),
                     'p2': (1, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2-1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }
                     },
                    {'p1': (1, 3.5),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }
                     },
                    {'p1': (4, 0),
                     'p2': (5, 3.5),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     }
                     },
                    {'p1': (2, 4),
                     'p2': (4, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                         'ha': 'right',
                     }
                     },
                ],
            },
        ),
        ]
)

kongruenzsatze_kennenlernen = QuestionSet(
    grade='7',
    capital='Dreiecke und Vielecke',
    subcapital='Kongruenz und Kongruenzsätze',
    title='Kongruenzsätze kennenlernen',
    instruction='',
    question_type='MC',
    questions=[
        Question(
            formula='Nach dem Kongruenzsatz <b>sss</b> sind Dreiecke, '
                    'die in allen _____ übereinstimmen, kongruent zueinander.',
            correct='drei Seiten',
            wrong_1='drei Winkeln',
            variables={
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 3),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'b',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (3, 3),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'a',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                     }},
                     ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (3, 3),
                     'text': 'α',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (3, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 0),
                     'p1': (3, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Nach dem Kongruenzsatz <b>wsw</b> sind Dreiecke, die in _____ und _____ übereinstimmen, '
                    'kongruent zueinander.',
            correct='einer Seite|einem Winkel; zwei Innenwinkeln|dem gegenüber liegenden Winkel',
            variables={
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 3),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'b',
                     'text_kw': {
                         'color': 'black',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (3, 3),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'a',
                     'text_kw': {
                         'color': 'black',
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                     }},
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (3, 3),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (3, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 0),
                     'p1': (3, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                ],
            },
        ),
        Question(
            formula='Nach dem Kongruenzsatz <b>sws</b> sind Dreiecke, die in _____ und _____ übereinstimmen, '
                    'kongruent zueinander.',
            correct='zwei Seiten|zwei Winkel; dem eingeschlossenen Winkel|einem gegenüber liegenden Winkel',
            variables={
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 3),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'b',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (3, 3),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'a',
                     'text_kw': {
                         'color': 'black',
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                     }},
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (3, 3),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (3, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (5, 0),
                     'p1': (3, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
        Question(
            formula='Nach dem Kongruenzsatz <b>Ssw</b> sind Dreiecke, die in _____ und dem der _____ Seite '
                    'gegenüber liegenden Winkel übereinstimmen, kongruent zueinander.',
            correct='zwei Seiten|zwei Winkel; längeren|kürzeren',
            variables={
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'lines': [
                    {'p1': (0, 0),
                     'p2': (1.5, 3),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'b',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'lightblue',
                     'zorder': 3,
                     'text': 'c',
                     'text_kw': {
                         'color': 'tab:blue',
                         'rotation': 0,
                         'fontsize': 'large',
                         'va': 'top',
                     }},
                    {'p1': (1.5, 3),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     'text': 'a',
                     'text_kw': {
                         'color': 'black',
                         'rotation': 0,
                         'fontsize': 'large',
                         'ha': 'left',
                     }},
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (1.5, 3),
                     'text': 'α',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                    {'xy': (1.5, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (1.5, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'lightgrey',
                     },
                ],
            },
        ),
    ]
)

question_sets = [
    winkel_berechnen_1,
    winkel_berechnen_2,
    satz_des_thales_anwenden,
    winkel_beschriebener_dreiecke_berechnen,
    kongruenzsatze_anwenden_1,
    kongruenzsatze_kennenlernen,
]
