from questions import Question, QuestionSet
from random import randint, choice, randrange
from definitions.common import randdecimal, male_names, female_names, numbers, weekdays, measurement_units

flacheninhalte_und_umfang_von_rechtecken = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Flächeninhalte und Umfang von Rechtecken',
    instruction='Berechne den Flächeninhalt des Rechtecks',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>A = a * b <br> = ___*___ <br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1*v2}} {{units}}^2',
            variables={
                'v1': (randint, 4, 9),
                'v2': (randint, 8, 15),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': 'lightgreen',
                     'edgecolor': 'darkgreen',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'texts': [
                    {'x': '{{v2}}',
                     'y': '{{(v1/2)}}',
                     's': ' {{v1}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'center',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = a * b <br> = ___*___ <br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1*v2}} {{units}}^2',
            variables={
                'v1': (randint, 8, 15),
                'v2': (randint, 3, 7),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': '#FECB85',
                     'edgecolor': 'darkorange',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'texts': [
                    {'x': '{{v2}}',
                     'y': '{{(v1/2)}}',
                     's': ' {{v1}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'center',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang des Rechtecks',
            formula='<mat>U = 2*(a+b)<br> = 2*(___+___)<br> = 2*___<br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1+v2}} {{units}};{{2*(v1+v2)}} {{units}}',
            variables={
                'v1': (randint, 4, 9),
                'v2': (randint, 8, 15),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': 'lightgreen',
                     'edgecolor': 'darkgreen',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'texts': [
                    {'x': '{{v2}}',
                     'y': '{{(v1/2)}}',
                     's': ' {{v1}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'center',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang des Rechtecks',
            formula='<mat>U = 2*(a+b)<br> = 2*(___+___)<br> = 2*___<br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1+v2}} {{units}};{{2*(v1+v2)}} {{units}}',
            variables={
                'v1': (randint, 8, 15),
                'v2': (randint, 3, 7),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': '#FECB85',
                     'edgecolor': 'darkorange',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'texts': [
                    {'x': '{{v2}}',
                     'y': '{{(v1/2)}}',
                     's': ' {{v1}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'center',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ]
            },
        ),
    ]
)

flacheninhalte_und_umfang_von_parallelogrammen = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Flächeninhalte und Umfang von Parallelogrammen',
    instruction='Berechne den Flächeninhalt des Parallelogramms',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>A = g * h <br> = ___*___<br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1*v2}} {{units}}^2',
            variables={
                'v1': (randint, 6, 10),
                'v2': (randint, 8, 15),
                'v3': (randint, 1, 3),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+v3+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{v3}}', '{{v1}}'), ('{{v2+v3}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': 'orchid',
                     'edgecolor': 'darkviolet',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v3+2}}', 0),
                     'p2': ('{{v3+2}}', '{{v1}}'),
                     'color': 'white',
                     'zorder': 15,
                     'text': ' {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)+v3}}',
                     'y': -0.2,
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = g * h <br> = ___*___<br> = ___</mat>',
            correct='{{v1*10}} {{units}};{{v2*10}} {{units}};{{v1*v2*100}} {{units}}^2',
            variables={
                'v1': (randint, 6, 10),
                'v2': (randint, 8, 15),
                'v3': (randint, 1, 3),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+v3+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [('{{v3}}', 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2+v3}}', 0)],
                     'closed': True,
                     'facecolor': 'pink',
                     'edgecolor': 'mediumvioletred',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v3+2}}', 0),
                     'p2': ('{{v3+2}}', '{{v1}}'),
                     'color': 'white',
                     'zorder': 15,
                     'text': '{{v1*10}} {{units}} ',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'right',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)}}',
                     'y': -0.2,
                     's': '{{v2*10}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = g * h <br> = ___*___<br> = ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1*v2}} {{units}}^2',
            variables={
                'v1': (randint, 7, 10),
                'v2': (randint, 3, 5),
                'v3': (randint, 4, 7),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+v3+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{v3}}', '{{v1}}'), ('{{v2+v3}}', '{{v1}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': 'wheat',
                     'edgecolor': 'tab:orange',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2+v3-2}}', 0),
                     'p2': ('{{v2+v3-2}}', '{{v1}}'),
                     'color': 'tab:blue',
                     'zorder': 15,
                     'text': ' h = {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                    {'p1': (-3, 0),
                     'p2': ('{{v2+v3+3}}', 0),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'zorder': 15,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)}}',
                     'y': -0.2,
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang des Parallelogramms',
            formula='<mat>U = 2*(___+___)<br>= 2*___<br>= ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1+v2}} {{units}};{{2*(v1+v2)}} {{units}}',
            variables={
                'v1': (randint, 5, 9),
                'v2': (randint, 6, 12),
                'v3': (randint, 2, 4),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+v3+1}}',
                                'ymin': '-1',
                                'ymax': '{{v1+1}}'},
                'polygons': [
                    {'xy': [('{{v3}}', 0), (0, '{{v1}}'), ('{{v2}}', '{{v1}}'), ('{{v2+v3}}', 0)],
                     'closed': True,
                     'facecolor': 'lightgreen',
                     'edgecolor': 'darkgreen',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v3+3}}', 0),
                     'p2': ('{{v3+3}}', '{{v1}}'),
                     'color': 'tab:blue',
                     'zorder': 15,
                     'text': ' {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                    {'p1': ('{{v3}}', 0),
                     'p2': (0, '{{v1}}'),
                     'linewidth': '0',
                     'zorder': 15,
                     'text': ' {{((v1**2+v3**2)**0.5)|round(0, "ceil")|int}} {{units}}  ',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'right',
                     }
                     },
                    {'p1': ('{{v2+v3}}', 0),
                     'p2': ('{{v2}}', '{{v1}}'),
                     'linewidth': 0,
                     'zorder': 15,
                     'text': ' {{((v1**2+v3**2)**0.5)|round(0, "ceil")|int}} {{units}} ',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{((v2+v3)/2)}}',
                     'y': -0.2,
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ],
                'angles': [
                    {'xy': ('{{v3+3}}', 0),
                     'p1': ('{{v3+5}}', 0),
                     'p2': ('{{v3+3}}', 2),
                     'text': '•',
                     'text_kw': {'color': 'white'},
                     'size': 1.5,
                     'zorder': 15,
                     'color': 'white',
                     }
                ],
            },
        ),
    ]
)

flacheninhalte_von_trapezen = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Flächeninhalte von Trapezen',
    instruction='Berechne den Flächeninhalt des Trapezes',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>A = 1/2 * (a + c) * h<br>'
                    '=1/2*(___+___)*___<br>'
                    '=1/2*___*{{v3}} {{units}} <br>= ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v3}} {{units}};'
                    '{{v1+v2}} {{units}};{{(((v1+v2)/2)*v3)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 3, 6),
                'v2': (randint, 7, 12),
                'v3': (choice, [6, 8, 10, 12]),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v3+1}}',
                                'ymin': '-1',
                                'ymax': '{{v2+1}}'},
                'polygons': [
                    {'xy': [(0, '{{(v2/2)-(v1/2)}}'), (0, '{{(v2/2)+(v1/2)}}'), ('{{v3}}', '{{v2}}'), ('{{v3}}', 0)],
                     'closed': True,
                     'facecolor': '#E6EDA0',
                     'edgecolor': 'yellowgreen',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, '{{v2/2}}'),
                     'p2': ('{{v3}}', '{{v2/2}}'),
                     'color': 'black',
                     'text': '{{v3}} {{units}}',
                     'zorder': 15,
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'va': 'bottom',
                     }
                     },
                ],
                'texts': [
                    {'x': -0.2,
                     'y': '{{(v2/2)}}',
                     's': '{{v1}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'right',
                     },
                    {'x': '{{v3+0.2}}',
                     'y': '{{(v2/2)}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = 1/2 * (a + c) * h<br>'
                    '=1/2*(___+___)*___<br>'
                    '=1/2*___*{{v3}} {{units}} <br>= ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v3}} {{units}};'
                    '{{v1+v2}} {{units}};{{(((v1+v2)/2)*v3)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 3, 6),
                'v2': (randint, 7, 12),
                'v3': (choice, [6, 8, 10, 12]),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{(v2/2)-(v1/2)}}', '{{v3}}'), ('{{(v2/2)+(v1/2)}}', '{{v3}}'), ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': '#E6EDA0',
                     'edgecolor': 'yellowgreen',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', '{{v3}}'),
                     'p2': ('{{v2/2}}', 0),
                     'color': 'black',
                     'text': '{{v3}} {{units}}',
                     'zorder': 15,
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'left',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)}}',
                     'y': -0.2,
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     },
                    {'x': '{{(v2/2)}}',
                     'y': '{{v3+0.2}}',
                     's': '{{v1}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = 1/2 * (a + c) * h<br>'
                    '=1/2*(___+___)*___<br>'
                    '=1/2*___*{{v3}} {{units}} <br>= ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v3}} {{units}};'
                    '{{(v1+v2)|round|int}} {{units}};{{(((v1+v2)/2)*v3)|round|int}} {{units}}^2',
            variables={
                'v1': (choice, [2.5, 3.5, 4.5, 5.5]),
                'v2': (choice, [6.5, 7.5, 8.5, 9.5]),
                'v3': (randrange, 4, 8, 2),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{(v2/2)-(v1/2)-0.5}}', '{{v3}}'), ('{{(v2/2)+(v1/2)-0.5}}', '{{v3}}'),
                            ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': '#FECB85',
                     'edgecolor': 'darkorange',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2-1}}', '{{v3}}'),
                     'p2': ('{{v2/2-1}}', 0),
                     'color': 'black',
                     'text': ' {{v3}} {{units}}',
                     'zorder': 15,
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)-0.5}}',
                     'y': -0.2,
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     },
                    {'x': '{{(v2/2)-0.5}}',
                     'y': '{{v3+0.2}}',
                     's': '{{v1}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = 1/2 * (a + c) * h<br>'
                    '=1/2*(___+___)*___<br>'
                    '=1/2*___*{{v3}} {{units}} <br>= ___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v3}} {{units}};'
                    '{{(v1+v2)|round|int}} {{units}};{{(((v1+v2)/2)*v3)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 3, 6),
                'v2': (randint, 7, 10),
                'v3': (choice, [6, 8, 10, 12]),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v2+1}}',
                                'ymin': '-1',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [('{{v2-v1}}', 0), (0, '{{v3}}'), ('{{v2}}', '{{v3}}'),
                            ('{{v2}}', 0)],
                     'closed': True,
                     'facecolor': '#92CBF7',
                     'edgecolor': '#298AE2',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2}}', '{{v3}}'),
                     'p2': ('{{v2}}', 0),
                     'color': 'black',
                     'text': ' {{v3}} {{units}}',
                     'zorder': 15,
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)}}',
                     'y': '{{v3+0.2}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     },
                    {'x': '{{v2-(v1/2)}}',
                     'y': -0.2,
                     's': '{{v1}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A = 1/2 * (a + c) * h<br>'
                    '=1/2*(___+___)*___<br>'
                    '=1/2*___*{{v3}} {{units}} <br>= ___</mat>',
            correct='{{v1}} {{units}};{{v1+v4}} {{units}};{{v3}} {{units}};'
                    '{{(v1+v1+v4)|round|int}} {{units}};{{(((v1+v1+v4)/2)*v3)|round|int}} {{units}}^2',
            variables={
                'v1': (choice, [3.5, 4.5, 5.5, 6.5]),
                'v2': (randint, 2, 4),
                'v3': (choice, [6, 8, 10, 12]),
                'v4': (choice, [1, 3]),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '{{v1+v2+v4+1}}',
                                'ymin': '-1',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{v2}}', '{{v3}}'), ('{{v1+v2+v4}}', '{{v3}}'), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': 'wheat',
                     'edgecolor': 'tab:orange',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v1+v2+v4-1.5}}', 0),
                     'p2': ('{{v1+v2+v4-1.5}}', '{{v3}}'),
                     'color': 'black',
                     'zorder': 15,
                     'text': ' h = {{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'rotation': 0,
                         'ha': 'left',
                     }
                     },
                    {'p1': (-3, 0),
                     'p2': ('{{v1+v2+v4+3}}', 0),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'zorder': 15,
                     },
                ],
                'texts': [
                    {'x': '{{(v1/2)}}',
                     'y': -0.2,
                     's': '{{v1}} {{units}}',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{v2+((v1+v4)/2)}}',
                     'y': '{{v3+0.2}}',
                     's': '{{v1+v4}} {{units}}',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'center',
                     }
                ]
            },
        ),
    ]
)

flacheninhalte_von_drachenvierecken = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Flächeninhalte von Drachenvierecken',
    instruction='Berechne den Flächeninhalt des Drachenvierecks.',
    question_type='gap',
    questions=[
        Question(
            formula='<mat >A||=1/2*e*f<br>||=1/2*___*___<br>||=____</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{((v1*v2)/2)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 4, 9),
                'v2': (choice, [4, 6, 8]),
                'v3': (randint, 1, 3),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2}}',
                                'ymin': '0',
                                'ymax': '{{v1}}'},
                'polygons': [
                    {'xy': [('{{v2/2}}', 0), (0, '{{v1-v3}}'), ('{{v2/2}}', '{{v1}}'), ('{{v2}}', '{{v1-v3}}')],
                     'closed': True,
                     'facecolor': '#B4EBF1',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2}}', '{{v1}}'),
                     'color': '#934CB4',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 15,
                     },
                    {'p1': (0, '{{v1-v3}}'),
                     'p2': ('{{v2}}', '{{v1-v3}}'),
                     'color': '#43A6F0',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 15,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/2)+0.2}}',
                     'y': 0,
                     's': ' {{v1}} {{units}}',
                     'fontsize': 'x-large',
                     'color': '#934CB4',
                     'va': 'top',
                     'ha': 'left',
                     },
                    {'x': '{{(v2+0.1)}}',
                     'y': '{{v1-v3+0.1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'x-large',
                     'color': '#43A6F0',
                     'va': 'bottom',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            formula='<mat >A||=1/2*e*f<br>||=1/2*___*___<br>||=____</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{((v1*v2)/2)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 4, 9),
                'v2': (choice, [8, 10, 12, 14]),
                'v3': (randint, 1, 4),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2}}',
                                'ymin': '0',
                                'ymax': '{{v1}}'},
                'polygons': [
                    {'xy': [('{{v2-v3}}', 0), (0, '{{v1/2}}'), ('{{v2-v3}}', '{{v1}}'), ('{{v2}}', '{{v1/2}}')],
                     'closed': True,
                     'facecolor': '#F7BCD0',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2-v3}}', 0),
                     'p2': ('{{v2-v3}}', '{{v1}}'),
                     'color': '#934CB4',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 15,
                     },
                    {'p1': (0, '{{v1/2}}'),
                     'p2': ('{{v2}}', '{{v1/2}}'),
                     'color': '#43A6F0',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 15,
                     },
                ],
                'texts': [
                    {'x': '{{(v2-v3)-0.2}}',
                     'y': '{{v1*3/4}}',
                     's': '{{v1}} {{units}}',
                     'fontsize': 'x-large',
                     'color': '#934CB4',
                     'va': 'center',
                     'ha': 'right',
                     },
                    {'x': 2,
                     'y': '{{v1/2-0.1}}',
                     's': '{{v2}} {{units}}',
                     'fontsize': 'x-large',
                     'color': '#43A6F0',
                     'va': 'top',
                     'ha': 'left',
                     }
                ]
            },
        ),
    ]
)

flacheninhalte_von_dreiecken = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Flächeninhalte von Dreiecken',
    instruction='Berechne den Flächeninhalt des Dreiecks.',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>A=1/2*c*h_c<br>=1/2 * ___{{units}} * ___{{units}}<br>= ___{{units}}^2</mat>',
            correct='{{v1}};{{v2}};{{(v1*v2/2)|round|int}}',
            variables={
                'v1': (randrange, 20, 40, 2),
                'v2': (randrange, 12, 24, 2),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (4, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': 'c = {{v1}} {{units}}',
                     'text_kw': {
                         'xytext': (0, -4),
                         'textcoords': 'offset points',
                         'fontsize': 'large',
                         'va': 'top',
                     },
                     },
                    {'p1': (4, 0),
                     'p2': (4, 3),
                     'color': 'black',
                     'linewidth': 2,
                     'text': 'h_c = {{v2}} {{units}}',
                     'text_kw': {
                         'xytext': (-4, 0),
                         'textcoords': 'offset points',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'center',
                     },
                     },
                    {'p1': (0, 0),
                     'p2': (4, 3),
                     'linewidth': 0,
                     'text': 'a',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'bottom',
                     }},
                    {'p1': (4, 3),
                     'p2': (5, 0),
                     'text': ' b',
                     'linewidth': 0,
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                ],
                'angles': [
                    {'xy': (4, 0),
                     'p1': (5, 0),
                     'p2': (4, 3),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A=1/2*a*h_a<br>=1/2 * ___{{units}} * ___{{units}}<br>= ___{{units}}^2</mat>',
            correct='{{v1}};{{v2}};{{(v1*v2/2)|round|int}}',
            variables={
                'v1': (randrange, 20, 40, 2),
                'v2': (randrange, 12, 24, 2),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3.5'},
                'polygons': [
                    {'xy': [(0, 1), (2.5, 3.5), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 1),
                     'p2': (2.5, 3.5),
                     'linewidth': 0,
                     'text': 'a = {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     },
                     },
                    {'p1': (2, 3),
                     'p2': (5, 0),
                     'color': 'black',
                     'linewidth': 2,
                     'text': 'h_a = {{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                         'xytext': (0, 6),
                         'textcoords': 'offset points',
                     },
                     },
                    {'p1': (2.5, 3.5),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': 'b',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                    {'p1': (0, 1),
                     'p2': (5, 0),
                     'text': 'c',
                     'linewidth': 0,
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'top',
                     }},
                ],
                'angles': [
                    {'xy': (2, 3),
                     'p1': (0, 1),
                     'p2': (5, 0),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A=1/2*c*h_c<br>=1/2 * ___{{units}} * ___{{units}}<br>= ___{{units}}^2</mat>',
            correct='{{v1}};{{v2}};{{(v1*v2/2)|round|int}}',
            variables={
                'v1': (randrange, 10, 20, 2),
                'v2': (randrange, 12, 24, 2),
                'v3': (randint, 10, 20),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{(v1+v3)/5}}',
                                'ymin': '0',
                                'ymax': '{{v2/5}}'},
                'polygons': [
                    {'xy': [(0, 0), ('{{(v1+v3)/5}}', '{{v2/5}}'), ('{{(v1)/5}}', 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': ('{{(v1+v3)/5}}', '{{v2/5}}'),
                     'linewidth': 0,
                     'text': 'a ',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'va': 'bottom',
                         'ha': 'right',
                     },
                     },
                    {'p1': ('{{v1/5}}', 0),
                     'p2': ('{{(v1+v3)/5}}', '{{v2/5}}'),
                     'linewidth': 0,
                     'text': ' b',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     },
                     },
                    {'p1': (0, 0),
                     'p2': ('{{v1/5}}', 0),
                     'linewidth': 0,
                     'text': 'c = {{v1}} {{units}}',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'xytext': (0, -6),
                         'textcoords': 'offset points',
                         'va': 'top',
                     }},
                    {'p1': ('{{(v1+v3)/5}}', 0),
                     'p2': ('{{(v1+v3)/5}}', '{{v2/5}}'),
                     'text': 'h_c = {{v2}} {{units}}',
                     'linewidth': 2,
                     'color': 'black',
                     'linestyle': 'dashed',
                     'text_kw': {
                         'fontsize': 'large',
                         'xytext': (4, 0),
                         'ha': 'left',
                         'textcoords': 'offset points',
                     }},
                    {'p1': ('{{(v1)/5}}', 0),
                     'p2': ('{{(v1+v3)/5}}', 0),
                     'linewidth': 1,
                     'color': 'grey',
                     'linestyle': 'dashed',
                     },
                ],
                'angles': [
                    {'xy': ('{{(v1+v3)/5}}', 0),
                     'p1': ('{{(v1+v3)/5}}', '{{v2/5}}'),
                     'p2': ('{{(v1)/5}}', 0),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>A=1/2*a*h_a<br>=1/2 * ___{{units}} * ___{{units}}<br>= ___{{units}}^2</mat>',
            correct='{{v1}};{{v2}};{{(v1*v2/2)|round|int}}',
            variables={
                'v1': (randrange, 30, 50, 2),
                'v2': (randrange, 15, 25),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '4.75',
                                'ymin': '0',
                                'ymax': '2.75'},
                'polygons': [
                    {'xy': [(0, 0.5), (4, 0), (4.5, 2.75)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0.5),
                     'p2': (4.5, 2.75),
                     'linewidth': 0,
                     'text': 'a = {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     },
                     },
                    {'p1': (3, 2),
                     'p2': (4, 0),
                     'color': 'black',
                     'linewidth': 2,
                     'text': 'h_a = {{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                         'xytext': (0, -2),
                         'textcoords': 'offset points',
                     },
                     },
                    {'p1': (4, 0),
                     'p2': (4.5, 2.75),
                     'linewidth': 0,
                     'text': ' b',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'top',
                     }},
                    {'p1': (0, 0.5),
                     'p2': (4, 0),
                     'text': 'c',
                     'linewidth': 0,
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'top',
                     }},
                ],
                'angles': [
                    {'xy': (3, 2),
                     'p1': (0, 0.5),
                     'p2': (4, 0),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
    ]
)

hohe_berechnen = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Höhe berechnen',
    instruction='Berechne den Höhe des Dreiecks.',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>h_c = (2*A_ABC)/c <br>'
                    '= (2*___{{units}}^2)/(___{{units}}) <br>= ___{{units}}',
            correct='{{(v1*v2/2)|round|int}};{{v2}};{{v1}}',
            variables={
                'v1': (randrange, 20, 40, 2),
                'v2': (randrange, 12, 24, 2),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (1, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': 'c = {{v1}} {{units}}',
                     'text_kw': {
                         'xytext': (0, -4),
                         'textcoords': 'offset points',
                         'fontsize': 'large',
                         'va': 'top',
                     },
                     },
                    {'p1': (1, 0),
                     'p2': (1, 3),
                     'color': 'tab:blue',
                     'linewidth': 2,
                     'text': 'h_a = ? {{units}}',
                     'text_kw': {
                         'xytext': (4, 0),
                         'textcoords': 'offset points',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'center',
                     },
                     },
                    {'p1': (0, 0),
                     'p2': (1, 3),
                     'linewidth': 0,
                     'text': 'a ',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'bottom',
                     }},
                    {'p1': (1, 3),
                     'p2': (5, 0),
                     'text': ' b',
                     'linewidth': 0,
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                ],
                'texts': [
                    {'x': 5,
                     'y': 3,
                     's': 'A = {{(v1*v2/2)|round|int}} {{units}}²',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'right',
                     }
                ],
                'angles': [
                    {'xy': (1, 0),
                     'p1': (5, 0),
                     'p2': (1, 3),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>h_a = (2*A_ABC)/b<br>'
                    '= (2*___{{units}}^2)/(___{{units}}) <br>'
                    '= ___{{units}}',
            correct='{{(v1*v2/2)|round|int}};{{v2}};{{v1}}',
            variables={
                'v1': (randrange, 20, 40, 2),
                'v2': (randrange, 12, 24, 2),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(0, 0), (1, 4), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (1, 4),
                     'linewidth': 0,
                     'text': 'a = {{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     },
                     },
                    {'p1': (0.3125, 1.25),
                     'p2': (5, 0),
                     'color': 'tab:blue',
                     'linewidth': 2,
                     'text': 'h_a = ? {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                         'xytext': (0, 6),
                         'textcoords': 'offset points',
                     },
                     },
                    {'p1': (1, 4),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': 'b',
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'left',
                         'va': 'bottom',
                     }},
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'c',
                     'linewidth': 0,
                     'text_kw': {
                         'rotation': '0',
                         'fontsize': 'large',
                         'ha': 'right',
                         'va': 'top',
                     }},
                ],
                'texts': [
                    {'x': 5,
                     'y': 4,
                     's': 'A = {{(v1*v2/2)|round|int}} {{units}}²',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'right',
                     }
                ],
                'angles': [
                    {'xy': (0.3125, 1.25),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': '•',
                     'text_kw': {'color': 'black'},
                     'size': 1,
                     'zorder': 15,
                     'color': 'black',
                     }
                ]
            },
        ),
    ]
)

umfang_berechnen = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Flächeninhalte und Umfang von Vielecken',
    title='Umfang berechnen',
    instruction='Berechne den Umfang des Dreiecks.',
    question_type='gap',
    questions=[
        Question(
            formula="<mat align='rl'>U = ___{{units}}+___{{units}}+___{{units}} <br>= ___{{units}}</mat>",
            correct='{{v1}};{{v2}};{{v3}};{{v1+v2+v3}}',
            variables={
                'v1': (randint, 12, 19),
                'v2': (randint, 12, 19),
                'v3': (randint, 7, 11),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (3.5, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': '{{v1}} {{units}}',
                     'text_kw': {
                         'xytext': (0, -4),
                         'textcoords': 'offset points',
                         'fontsize': 'large',
                         'va': 'top',
                     },
                     },
                    {'p1': (0, 0),
                     'p2': (3.5, 3),
                     'linewidth': 0,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     },
                     },
                    {'p1': (3.5, 3),
                     'p2': (5, 0),
                     'linewidth': 0,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                ],
            },
        ),
        Question(
            formula="<mat align='rl'>U = ___{{units}}+___{{units}}+___{{units}} <br>= ___{{units}}</mat>",
            correct='{{v1}};{{v2}};{{v3}};{{v1+v2+v3}}',
            variables={
                'v1': (randint, 5, 9),
                'v2': (randint, 18, 22),
                'v3': (randint, 12, 17),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '4',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(0, 4), (2.5, 4), (4, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (0, 4),
                     'p2': (2.5, 4),
                     'linewidth': 0,
                     'text': '{{v1}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     },
                     },
                    {'p1': (0, 4),
                     'p2': (4, 0),
                     'linewidth': 0,
                     'text': '{{v2}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'top',
                     },
                     },
                    {'p1': (2.5, 4),
                     'p2': (4, 0),
                     'linewidth': 0,
                     'text': '{{v3}} {{units}}',
                     'text_kw': {
                         'fontsize': 'large',
                         'va': 'bottom',
                     }},
                ],
            },
        ),
    ]
)

prismen_mit_viereckiger_grundflache = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Oberflächen und Volumen von Prismen',
    title='Prismen mit viereckiger Grundfläche',
    instruction='',
    question_type='gap',
    questions=[
        Question(
            instruction='Berechne die Grundfläche A_G. Die Grundfläche ist ein Parallelogramm.',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>h_a = {{v2}} {{units}}</mat><br>'
                    '<mat>A_G = a*h_a<br>=___*___<br>=___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{v1*v2}} {{units}}^2',
            variables={
                'v1': (randint, 6, 9),
                'v2': (choice, [4]),
                'v3': (randint, 4, 8),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v1+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (3, 1.5), ('{{v1+3}}', 1.5), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [('{{v1}}', 0), ('{{v1}}', '{{v3}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1+3}}', 1.5)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [(0, 0), (0, '{{v3}}'), ('{{v1}}', '{{v3}}'), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': (3, '{{v3+1.5}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': ('{{v1+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v1/2}}', 0),
                     'p2': ('{{v1/2+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                ],
                'texts': [
                    {'x': '{{(v1/2)}}',
                     'y': -0.1,
                     's': 'a',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{(v1+1.9)}}',
                     'y': '{{0.75}}',
                     's': 'b',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': -0.1,
                     'y': '{{v3/2}}',
                     's': 'h',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'right',
                     },
                    {'x': '{{(v1/2)+1.9}}',
                     'y': '{{0.75}}',
                     's': 'h_a',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang der Grundfläche U_G. Die Grundfläche ist ein Parallelogramm.',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>b = {{v2}} {{units}}</mat><br>'
                    '<mat>U_G = 2*___ + 2*___<br>=___</mat>',
            correct='{{v1}} {{units}};{{v2}} {{units}};{{2*(v1+v2)}} {{units}}',
            variables={
                'v1': (randint, 6, 9),
                'v2': (choice, [4]),
                'v3': (randint, 4, 8),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v1+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (3, 1.5), ('{{v1+3}}', 1.5), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [('{{v1}}', 0), ('{{v1}}', '{{v3}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1+3}}', 1.5)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [(0, 0), (0, '{{v3}}'), ('{{v1}}', '{{v3}}'), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': (3, '{{v3+1.5}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': ('{{v1+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v1/2}}', 0),
                     'p2': ('{{v1/2+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                ],
                'texts': [
                    {'x': '{{(v1/2)}}',
                     'y': -0.1,
                     's': 'a',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{(v1+1.9)}}',
                     'y': '{{0.75}}',
                     's': 'b',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': -0.1,
                     'y': '{{v3/2}}',
                     's': 'h',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'right',
                     },
                    {'x': '{{(v1/2)+1.9}}',
                     'y': '{{0.75}}',
                     's': 'h_a',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Oberflächeninhalt O_P',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>b = {{v2}} {{units}}</mat><br>'
                    '<mat>h = {{v3}} {{units}}</mat><br>'
                    '<mat>O_P = 2*A_G+U_G*h<br>=2*___+___*___ <br>=___+___<br>=___</mat>',
            correct='{{v1*v2}} {{units}}^2;{{2*(v1+v2)}} {{units}};{{v3}} {{units}};'
                    '{{2*v1*v2}} {{units}}^2;{{2*(v1+v2)*v3}} {{units}}^2;{{2*v1*v2 + 2*(v1+v2)*v3}} {{units}}^2',
            variables={
                'v1': (randint, 6, 9),
                'v2': (choice, [4]),
                'v3': (randint, 4, 8),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v1+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (3, 1.5), ('{{v1+3}}', 1.5), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [('{{v1}}', 0), ('{{v1}}', '{{v3}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1+3}}', 1.5)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [(0, 0), (0, '{{v3}}'), ('{{v1}}', '{{v3}}'), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': (3, '{{v3+1.5}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': ('{{v1+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v1/2}}', 0),
                     'p2': ('{{v1/2+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                ],
                'texts': [
                    {'x': '{{(v1/2)}}',
                     'y': -0.1,
                     's': 'a',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{(v1+1.9)}}',
                     'y': '{{0.75}}',
                     's': 'b',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': -0.1,
                     'y': '{{v3/2}}',
                     's': 'h',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'right',
                     },
                    {'x': '{{(v1/2)+1.9}}',
                     'y': '{{0.75}}',
                     's': 'h_a',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne das Volumen V_P des Prismas',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>h_a = {{v2}} {{units}}</mat><br>'
                    '<mat>h = {{v3}} {{units}}</mat><br>'
                    '<mat>V_P = A_G*h<br>||=||___*___<br>||=||___</mat>',
            correct='{{v1*v2}} {{units}}^2;{{v3}} {{units}};{{v1*v2*v3}} {{units}}^3',
            variables={
                'v1': (randint, 6, 9),
                'v2': (choice, [4]),
                'v3': (randint, 4, 8),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v1+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+1}}'},
                'polygons': [
                    {'xy': [(0, 0), (3, 1.5), ('{{v1+3}}', 1.5), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': '#4EACF4',
                     'alpha': 0.6,
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [(0, '{{v3}}'), (3, '{{v3+1.5}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [('{{v1}}', 0), ('{{v1}}', '{{v3}}'), ('{{v1+3}}', '{{v3+1.5}}'), ('{{v1+3}}', 1.5)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                    {'xy': [(0, 0), (0, '{{v3}}'), ('{{v1}}', '{{v3}}'), ('{{v1}}', 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 6,
                     },
                ],
                'lines': [
                    {'p1': (0, 0),
                     'p2': (3, 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': (3, '{{v3+1.5}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, 1.5),
                     'p2': ('{{v1+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v1/2}}', 0),
                     'p2': ('{{v1/2+3}}', 1.5),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                ],
                'texts': [
                    {'x': '{{(v1/2)}}',
                     'y': -0.1,
                     's': 'a',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'center',
                     },
                    {'x': '{{(v1+1.9)}}',
                     'y': '{{0.75}}',
                     's': 'b',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': -0.1,
                     'y': '{{v3/2}}',
                     's': 'h',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'right',
                     },
                    {'x': '{{(v1/2)+1.9}}',
                     'y': '{{0.75}}',
                     's': 'h_a',
                     'fontsize': 'large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
    ]
)

prismen_mit_viereckiger_grundflache_2 = QuestionSet(
    grade='7',
    capital='Flächen und Körper',
    subcapital='Oberflächen und Volumen von Prismen',
    title='Prismen mit viereckiger Grundfläche',
    instruction='',
    question_type='gap',
    questions=[
        Question(
            instruction='Berechne die Grundfläche A_G. Die Grundfläche ist ein Parallelogramm.',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>e = {{v2}} {{units}}</mat><br>'
                    '<mat>f = {{v3}} {{units}}</mat><br>'
                    '<mat>h = {{v4}} {{units}}</mat><br>'
                    '<mat>A_G = 1/2*e*f<br>=___*___*___<br>=___</mat>',
            correct='1/2;{{v2}} {{units}};{{v3}} {{units}};{{(v2*v3/2)|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 8, 9),
                'v2': (randrange, 12, 16, 2),
                'v3': (randrange, 6, 8, 2),
                'v4': (randint, 4, 6),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+3}}'},
                'polygons': [
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [('{{v2/2+3}}', 3), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [('{{v2}}', '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [(0, '{{v3/2}}'), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'), ('{{v2/2}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, '{{v3/2+3}}'),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v2/2+3}}', 3),
                     'p2': ('{{v2+3}}', '{{v3/2+3}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (0, '{{v3/2}}'),
                     'p2': ('{{v2}}', '{{v3/2}}'),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2}}', '{{v3}}'),
                     'color': 'tab:blue',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/4)}}',
                     'y': '{{v3/2+0.1}}',
                     's': 'e',
                     'fontsize': 'x-large',
                     'color': 'tab:orange',
                     'va': 'bottom',
                     'ha': 'center',
                     'zorder': 10,
                     },
                    {'x': '{{v2/2+0.2}}',
                     'y': '{{v3/4}}',
                     's': 'f',
                     'fontsize': 'x-large',
                     'color': 'tab:blue',
                     'va': 'center',
                     'ha': 'left',
                     'zorder': 10,
                     },
                    {'x': '{{v2*3/4+0.4}}',
                     'y': '{{v3/4}}',
                     's': 'a',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': '{{v2+1.9}}',
                     'y': '{{v3/2+1.5}}',
                     's': 'h',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang der Grundfläche U_G. Die Grundfläche ist ein Parallelogramm.',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>e = {{v2}} {{units}}</mat><br>'
                    '<mat>f = {{v3}} {{units}}</mat><br>'
                    '<mat>h = {{v4}} {{units}}</mat><br>'
                    '<mat>U_G = 4*___<br>=___</mat>',
            correct='{{v1}} {{units}};{{v1*4}} {{units}}',
            variables={
                'v1': (randint, 8, 9),
                'v2': (randrange, 12, 16, 2),
                'v3': (randrange, 6, 8, 2),
                'v4': (randint, 4, 6),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+3}}'},
                'polygons': [
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [('{{v2/2+3}}', 3), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [('{{v2}}', '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [(0, '{{v3/2}}'), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'), ('{{v2/2}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, '{{v3/2+3}}'),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v2/2+3}}', 3),
                     'p2': ('{{v2+3}}', '{{v3/2+3}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (0, '{{v3/2}}'),
                     'p2': ('{{v2}}', '{{v3/2}}'),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2}}', '{{v3}}'),
                     'color': 'tab:blue',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/4)}}',
                     'y': '{{v3/2+0.1}}',
                     's': 'e',
                     'fontsize': 'x-large',
                     'color': 'tab:orange',
                     'va': 'bottom',
                     'ha': 'center',
                     'zorder': 10,
                     },
                    {'x': '{{v2/2+0.2}}',
                     'y': '{{v3/4}}',
                     's': 'f',
                     'fontsize': 'x-large',
                     'color': 'tab:blue',
                     'va': 'center',
                     'ha': 'left',
                     'zorder': 10,
                     },
                    {'x': '{{v2*3/4+0.4}}',
                     'y': '{{v3/4}}',
                     's': 'a',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': '{{v2+1.9}}',
                     'y': '{{v3/2+1.5}}',
                     's': 'h',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Oberflächeninhalt O_P',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>e = {{v2}} {{units}}</mat><br>'
                    '<mat>f = {{v3}} {{units}}</mat><br>'
                    '<mat>h = {{v4}} {{units}}</mat><br>'
                    '<mat>O_P = 2*A_G+U_G*h<br>=2*___+___*___ <br>=___+___<br>=___</mat>',
            correct='{{(v2*v3/2)|round|int}} {{units}}^2;{{4*v1}} {{units}};{{v4}} {{units}};'
                    '{{(v2*v3/2)|round|int}} {{units}}^2;{{4*v1*v4}} {{units}}^2;'
                    '{{((v2*v3/2)+(4*v1*v4))|round|int}} {{units}}^2',
            variables={
                'v1': (randint, 8, 9),
                'v2': (randrange, 12, 16, 2),
                'v3': (randrange, 6, 8, 2),
                'v4': (randint, 4, 6),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+3}}'},
                'polygons': [
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [('{{v2/2+3}}', 3), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [('{{v2}}', '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [(0, '{{v3/2}}'), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'), ('{{v2/2}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, '{{v3/2+3}}'),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v2/2+3}}', 3),
                     'p2': ('{{v2+3}}', '{{v3/2+3}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (0, '{{v3/2}}'),
                     'p2': ('{{v2}}', '{{v3/2}}'),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2}}', '{{v3}}'),
                     'color': 'tab:blue',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/4)}}',
                     'y': '{{v3/2+0.1}}',
                     's': 'e',
                     'fontsize': 'x-large',
                     'color': 'tab:orange',
                     'va': 'bottom',
                     'ha': 'center',
                     'zorder': 10,
                     },
                    {'x': '{{v2/2+0.2}}',
                     'y': '{{v3/4}}',
                     's': 'f',
                     'fontsize': 'x-large',
                     'color': 'tab:blue',
                     'va': 'center',
                     'ha': 'left',
                     'zorder': 10,
                     },
                    {'x': '{{v2*3/4+0.4}}',
                     'y': '{{v3/4}}',
                     's': 'a',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': '{{v2+1.9}}',
                     'y': '{{v3/2+1.5}}',
                     's': 'h',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne das Volumen V_P des Prismas',
            formula='<mat>a = {{v1}} {{units}}</mat><br>'
                    '<mat>e = {{v2}} {{units}}</mat><br>'
                    '<mat>f = {{v3}} {{units}}</mat><br>'
                    '<mat>h = {{v4}} {{units}}</mat><br>'
                    '<mat>V_P = A_G*h<br>||=||___*___<br>||=||___</mat>',
            correct='{{(v2*v3/2)|round|int}} {{units}}^2;{{v4}} {{units}};{{(v2*v3*v4/2)|round|int}} {{units}}^3',
            variables={
                'v1': (randint, 8, 9),
                'v2': (randrange, 12, 16, 2),
                'v3': (randrange, 6, 8, 2),
                'v4': (randint, 4, 6),
                'units': (choice, measurement_units),
            },
            image={
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '{{v2+3}}',
                                'ymin': '0',
                                'ymax': '{{v3+3}}'},
                'polygons': [
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 5,
                     },
                    {'xy': [('{{v2/2+3}}', 3), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': '#8FB2BF',
                     'alpha': 0.6,
                     'edgecolor': 'None',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [('{{v2/2}}', 0), (0, '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2}}', '{{v3/2}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [('{{v2}}', '{{v3/2}}'), ('{{v2/2}}', '{{v3}}'), ('{{v2/2+3}}', '{{v3+3}}'),
                            ('{{v2+3}}', '{{v3/2+3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'xy': [(0, '{{v3/2}}'), (3, '{{v3/2+3}}'), ('{{v2/2+3}}', '{{v3+3}}'), ('{{v2/2}}', '{{v3}}')],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': '#222',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'lines': [
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (3, '{{v3/2+3}}'),
                     'p2': ('{{v2/2+3}}', 3),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': ('{{v2/2+3}}', 3),
                     'p2': ('{{v2+3}}', '{{v3/2+3}}'),
                     'color': '#222',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 4,
                     },
                    {'p1': (0, '{{v3/2}}'),
                     'p2': ('{{v2}}', '{{v3/2}}'),
                     'color': 'tab:orange',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                    {'p1': ('{{v2/2}}', 0),
                     'p2': ('{{v2/2}}', '{{v3}}'),
                     'color': 'tab:blue',
                     'linestyle': 'dashed',
                     'linewidth': 2,
                     'zorder': 7,
                     },
                ],
                'texts': [
                    {'x': '{{(v2/4)}}',
                     'y': '{{v3/2+0.1}}',
                     's': 'e',
                     'fontsize': 'x-large',
                     'color': 'tab:orange',
                     'va': 'bottom',
                     'ha': 'center',
                     'zorder': 10,
                     },
                    {'x': '{{v2/2+0.2}}',
                     'y': '{{v3/4}}',
                     's': 'f',
                     'fontsize': 'x-large',
                     'color': 'tab:blue',
                     'va': 'center',
                     'ha': 'left',
                     'zorder': 10,
                     },
                    {'x': '{{v2*3/4+0.4}}',
                     'y': '{{v3/4}}',
                     's': 'a',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     },
                    {'x': '{{v2+1.9}}',
                     'y': '{{v3/2+1.5}}',
                     's': 'h',
                     'fontsize': 'x-large',
                     'va': 'center',
                     'ha': 'left',
                     }
                ]
            },
        ),
    ]
)

question_sets = [
    flacheninhalte_und_umfang_von_rechtecken,
    flacheninhalte_und_umfang_von_parallelogrammen,
    flacheninhalte_von_trapezen,
    flacheninhalte_von_drachenvierecken,
    flacheninhalte_von_dreiecken,
    hohe_berechnen,
    umfang_berechnen,
    prismen_mit_viereckiger_grundflache,
    prismen_mit_viereckiger_grundflache_2,
]
