from questions import Question, QuestionSet
from random import randint, choice, randrange
from definitions.common import randdecimal, male_names, female_names, numbers, weekdays, measurement_units

satz_des_thales = QuestionSet(
    grade='8',
    capital='Flächen',
    subcapital='Dreiecke',
    title='Satz des Thales',
    instruction='',
    question_type='gap',
    questions=[
        Question(
            instruction='Berechne die Winkel α und β. Berechne dafür zunächst die Winkel δ_1 und δ_2.',
            formula="<mat>δ_1 = ___°<br>"
                    "δ_2 = ___°<br>"
                    "α = ___° - ___° - ___° = ___°<br>"
                    "β = ___° - ___° - ___° = ___°<br></mat>",
            correct='{{180-v1}};{{180-v1}};'
                    '{{180}};{{90}};{{180-v1}};{{v1-90}};'
                    '{{180}};{{90}};{{180-v1}};{{v1-90}}',
            variables={
                'v1': (randint, 110, 130),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '-0.1',
                                'xmax': '5.1',
                                'ymin': '0',
                                'ymax': '2.5'},
                'lines': [
                    {'p1': (-0.1, 0),
                     'p2': (5.1, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (0.585, 1.605),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0.585, 1.605),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (2.925, 2.46),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.925, 2.46),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.5, 0.03),
                     'p2': (2.5, -0.03),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (2.5, 0),
                     'p1': (5, 0),
                     'p2': (0, 0),
                     'size': 5,
                     'zorder': 2,
                     'color': 'black',
                     'linewidth': 2,
                     },
                    {'xy': (0, 0),
                     'p1': (2.925, 2.46),
                     'p2': (0.585, 1.605),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (2.925, 2.46),
                     'p2': (0.585, 1.605),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (1.509, 1.269),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'None',
                     },
                    {'xy': (1.509, 1.269),
                     'p1': (0.585, 1.605),
                     'p2': (0, 0),
                     'text': 'δ_1',
                     'text_kw': {'color': 'darkgoldenrod',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'darkgoldenrod',
                     'facecolor': 'gold',
                     },
                    {'xy': (1.509, 1.269),
                     'p1': (5, 0),
                     'p2': (2.925, 2.46),
                     'text': 'δ_2',
                     'text_kw': {'color': 'darkgoldenrod',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'darkgoldenrod',
                     'facecolor': 'gold',
                     },
                ],
                'texts': [
                    {'x': 0,
                     'y': -0.05,
                     's': 'A',
                     'fontsize': 'large',
                     'ha': 'right',
                     'va': 'top',
                     },
                    {'x': 5,
                     'y': -0.05,
                     's': 'B',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'top',
                     },
                    {'x': 0.585,
                     'y': 1.605,
                     's': 'C_1 ',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'right',
                     },
                    {'x': 2.925,
                     'y': 2.5,
                     's': ' C_2',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'left',
                     },
                ]
            },
        ),
        Question(
            instruction='Berechne alle Winkel des Dreiecks ∆BCD.',
            formula="<mat>γ_1 = ___°<br>"
                    "γ_2 = ___° - γ_1 = ___° - ___° = ___°<br>"
                    "δ = ___°<br>"
                    "β = ___° - ___° - ___° = ___°<br></mat>",
            correct='{{v1}};'
                    '90;90;{{v1}};{{90-v1}};'
                    '{{90}};'
                    '{{180}};{{90}};{{90-v1}};{{v1}}',
            variables={
                'v1': (randint, 55, 65),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '-0.1',
                                'xmax': '5.1',
                                'ymin': '-1.25',
                                'ymax': '2.5'},
                'lines': [
                    {'p1': (-0.1, 0),
                     'p2': (5.1, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (0, 0),
                     'p2': (1.25, 2.165),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1.25, 2.165),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (1.25, 2.165),
                     'p2': (3.125, -1.08),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (3.125, -1.08),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (2.5, 0.03),
                     'p2': (2.5, -0.03),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (2.5, 0),
                     'p1': (5, 0),
                     'p2': (0, 0),
                     'size': 5,
                     'zorder': 2,
                     'color': 'black',
                     'linewidth': 2,
                     },
                    {'xy': (3.75, 0),
                     'p1': (2.5, 0),
                     'p2': (5, 0),
                     'size': 2.5,
                     'zorder': 2,
                     'color': 'black',
                     'linewidth': 2,
                     },
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (1.25, 2.165),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': 'None',
                     },
                    {'xy': (1.25, 2.165),
                     'p1': (0, 0),
                     'p2': (2.5, 0),
                     'text': 'γ_1',
                     'text_kw': {'color': 'darkgoldenrod',
                                 'fontsize': 'large'},
                     'size': 1.7,
                     'zorder': 2,
                     'color': 'darkgoldenrod',
                     'facecolor': 'gold',
                     },
                    {'xy': (1.25, 2.165),
                     'p1': (2.5, 0),
                     'p2': (5, 0),
                     'text': 'γ_2',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.7,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (5, 0),
                     'p1': (1.25, 2.165),
                     'p2': (3.125, -1.08),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                    {'xy': (3.125, -1.08),
                     'p1': (5, 0),
                     'p2': (2.5, 0),
                     'text': 'δ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': 'lightblue',
                     },
                ],
                'texts': [
                    {'x': 0,
                     'y': -0.05,
                     's': 'A',
                     'fontsize': 'large',
                     'ha': 'right',
                     'va': 'top',
                     },
                    {'x': 5,
                     'y': -0.05,
                     's': 'B',
                     'fontsize': 'large',
                     'ha': 'left',
                     'va': 'top',
                     },
                    {'x': 1.25,
                     'y': 2.165,
                     's': 'C ',
                     'fontsize': 'large',
                     'va': 'bottom',
                     'ha': 'right',
                     },
                    {'x': 2.5,
                     'y': -0.05,
                     's': 'M ',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'right',
                     },
                    {'x': 3.125,
                     'y': -1.08,
                     's': 'D ',
                     'fontsize': 'large',
                     'va': 'top',
                     'ha': 'right',
                     },
                ]
            },
        ),
    ]
)

winkel_berechnen_1_gap = QuestionSet(
    grade='8',
    capital='Flächen',
    subcapital='Dreiecke',
    title='Winkel berechnen (1)',
    instruction='Berechne den fehlenden Winkel.',
    question_type='gap',
    questions=[
        Question(
            formula='<mat>β = 180° - (___° + ___°)<br> '
                    '= 180° - ___°<br> = ___°</mat>',
            correct='{{v1}};{{v2}};{{v1+v2}};{{180-v1-v2}}',
            variables={
                'v1': (randint, 25, 35),
                'v2': (randrange, 95, 115),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (3, 3), (5, 2)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 2),
                     'p2': (3, 3),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'textposition': 'outside',
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (3, 3),
                     'p1': (0, 0),
                     'p2': (5, 2),
                     'text': '{{v2}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 2),
                     'p1': (3, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': 1.45,
                     'y': 1.5,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     },
                    {'x': 4.05,
                     'y': 2.5,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 2.5,
                     'y': 1,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'top',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>α = 180° - (___° + ___°)<br> '
                    '= 180° - ___°<br> = ___°</mat>',
            correct='90;{{v1}};{{90+v1}};{{90-v1}}',
            variables={
                'v1': (randint, 25, 35),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (0, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (0, 3),
                     'text': '·',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 0),
                     'p1': (0, 3),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (0, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': -0.05,
                     'y': 1.5,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'center',
                     },
                    {'x': 2.3,
                     'y': -0.05,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'top',
                     },
                    {'x': 2.7,
                     'y': 1.45,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            formula='<mat>γ = 180° - (___° + ___°)<br> '
                    '= 180° - ___°<br> = ___°</mat>',
            correct='{{v1}};{{v1}};{{v1*2}};{{180-v1*2}}',
            variables={
                'v1': (randint, 30, 40),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '2'},
                'polygons': [
                    {'xy': [(0, 0), (2.5, 2), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (2.5, 2),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 0),
                     'p1': (2.5, 2),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (2.5, 2),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': 1.2,
                     'y': 1,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     },
                    {'x': 3.8,
                     'y': 1,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 2.5,
                     'y': -0.05,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'top',
                     }
                ]
            },
        ),
    ]
)

winkel_berechnen_1_mc = QuestionSet(
    grade='8',
    capital='Flächen',
    subcapital='Dreiecke',
    title='Winkel berechnen (1)',
    instruction='Fülle die Lücken.',
    question_type='MC',
    questions=[
        Question(
            formula='Das ist ein _____, _____ Dreieck',
            correct='ungleichseitiges|gleichseitiges|gleichschenkliges;'
                    'stumpfwinkliges|rechtwinkliges|spitzwinkliges',
            variables={
                'v1': (randint, 25, 35),
                'v2': (randrange, 95, 115),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (3, 3), (5, 2)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 2),
                     'p2': (3, 3),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'textposition': 'outside',
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (3, 3),
                     'p1': (0, 0),
                     'p2': (5, 2),
                     'text': '{{v2}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 2),
                     'p1': (3, 3),
                     'p2': (0, 0),
                     'text': 'β',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': 1.45,
                     'y': 1.5,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     },
                    {'x': 4.05,
                     'y': 2.5,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 2.5,
                     'y': 1,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'top',
                     }
                ]
            },
        ),
        Question(
            formula='Das ist ein _____, _____ Dreieck',
            correct='ungleichseitiges|gleichseitiges|gleichschenkliges;'
                    'rechtwinkliges|stumpfwinkliges|spitzwinkliges',
            variables={
                'v1': (randint, 25, 35),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '3'},
                'polygons': [
                    {'xy': [(0, 0), (0, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (0, 3),
                     'text': '·',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 0),
                     'p1': (0, 3),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (0, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'α',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': -0.05,
                     'y': 1.5,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'center',
                     },
                    {'x': 2.3,
                     'y': -0.05,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'top',
                     },
                    {'x': 2.7,
                     'y': 1.45,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            formula='Das ist ein _____, _____ Dreieck',
            correct='gleichschenkliges|ungleichseitiges|gleichseitiges;'
                    'stumpfwinkliges|rechtwinkliges|spitzwinkliges',
            variables={
                'v1': (randint, 30, 40),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '5',
                                'ymin': '0',
                                'ymax': '2'},
                'polygons': [
                    {'xy': [(0, 0), (2.5, 2), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (5, 0),
                     'p2': (2.5, 2),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 0),
                     'p1': (2.5, 2),
                     'p2': (0, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (2.5, 2),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
                'texts': [
                    {'x': 1.2,
                     'y': 1,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     },
                    {'x': 3.8,
                     'y': 1,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 2.5,
                     'y': -0.05,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'top',
                     }
                ]
            },
        ),
    ]
)

winkel_berechnen_2 = QuestionSet(
    grade='8',
    capital='Flächen',
    subcapital='Dreiecke',
    title='Winkel berechnen (2)',
    instruction='Berechne die gesuchten Winkel des Dreiecks im Kopf. Berechne dafür zunächst die Hilfswinkel.',
    question_type='gap',
    questions=[
        Question(
            formula="<mat>α' = ___°<br> α = ___°<br> γ = ___°<br>β = ___°<br>β' = ___°</mat>",
            correct='{{180-v2}};{{180-v2}};{{180-v1}};{{v1+v2-180}};{{360-v1-v2}}',
            variables={
                'v1': (randint, 130, 150),
                'v2': (randint, 110, 130),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '-1',
                                'xmax': '6',
                                'ymin': '-1',
                                'ymax': '3.67'},
                'polygons': [
                    {'xy': [(0, 0), (3, 2), (4, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                    {'xy': [(3, 2), (4, 0), (6, 0), (4.5, 3)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (-1, 0),
                     'p2': (0, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4, 0),
                     'p2': (4.5, -1),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (4.5, 3),
                     'p2': (5.5, 3.67),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                ],
                'angles': [
                    {'xy': (0, 0),
                     'p1': (3, 2),
                     'p2': (-1, 0),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (0, 0),
                     'p1': (4, 0),
                     'p2': (3, 2),
                     'text': 'γ',
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                    {'xy': (4, 0),
                     'p1': (0, 0),
                     'p2': (4.5, -1),
                     'text': '{{v2}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (4, 0),
                     'p1': (3, 2),
                     'p2': (0, 0),
                     'text': "α'",
                     'text_kw': {'color': 'grey',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'grey',
                     'facecolor': 'whitesmoke',
                     },
                    {'xy': (6, 0),
                     'p1': (4.5, 3),
                     'p2': (0, 0),
                     'text': "α",
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                    {'xy': (4.5, 3),
                     'p1': (6, 0),
                     'p2': (5.5, 3.67),
                     'text': "β'",
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                    {'xy': (4.5, 3),
                     'p1': (0, 0),
                     'p2': (6, 0),
                     'text': "β",
                     'text_kw': {'color': 'grey',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'grey',
                     'facecolor': 'whitesmoke',
                     },
                ],
                'texts': [
                    {'x': 2,
                     'y': -0.05,
                     's': 'b',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'top',
                     },
                    {'x': 1.45,
                     'y': 1,
                     's': 'a',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     },
                    {'x': 5.3,
                     'y': 1.5,
                     's': 'c',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 3.55,
                     'y': 1,
                     's': 'd',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'bottom',
                     },
                    {'x': 0,
                     'y': 3,
                     's': 'c || d',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'center',
                     'va': 'center',
                     },
                ]
            },
        ),
        Question(
            formula="<mat>δ = ___°<br> γ = ___°<br> α = ___°</mat> ",
            correct='{{180-v1}};{{v1-v2}};{{180-v3-(v1-v2)}}',
            variables={
                'v1': (randint, 125, 135),
                'v2': (randint, 95, 105),
                'v3': (randint, 125, 135),
            },
            image={
                'draw_axes': False,
                'draw_grid': False,
                'axis_limits': {'xmin': '-1.5',
                                'xmax': '5.5',
                                'ymin': '0',
                                'ymax': '4'},
                'polygons': [
                    {'xy': [(3, 0), (-1, 3), (5, 0)],
                     'closed': True,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     'zorder': 3,
                     },
                ],
                'lines': [
                    {'p1': (-1.33, 4),
                     'p2': (0, 0),
                     'linewidth': 2,
                     'linestyle': 'dashed',
                     'color': 'black',
                     'zorder': 7,
                     },
                    {'p1': (0, 0),
                     'p2': (5.5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 3,
                     },
                    {'p1': (-1, 3),
                     'p2': (3, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 5,
                     },
                    {'p1': (-1, 3),
                     'p2': (5, 0),
                     'linewidth': 2,
                     'color': 'black',
                     'zorder': 9,
                     },
                ],
                'angles': [
                    {'xy': (-1, 3),
                     'p1': (5, 0),
                     'p2': (-1.33, 4),
                     'text': '{{v1}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (-1, 3),
                     'p1': (0, 0),
                     'p2': (5, 0),
                     'text': 'δ',
                     'text_kw': {'color': 'grey',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 8,
                     'color': 'grey',
                     'facecolor': 'whitesmoke',
                     },
                    {'xy': (-1, 3),
                     'p1': (3, 0),
                     'p2': (5, 0),
                     'text': "α",
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 3,
                     'zorder': 4,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                    {'xy': (0, 0),
                     'p1': (3, 0),
                     'p2': (-1, 3),
                     'text': '{{v2}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.5,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (3, 0),
                     'p1': (5, 0),
                     'p2': (-1, 3),
                     'text': '{{v3}}°',
                     'text_kw': {'color': 'black',
                                 'fontsize': 'large'},
                     'size': 1.2,
                     'zorder': 2,
                     'color': 'black',
                     'facecolor': '#92CBF7',
                     },
                    {'xy': (5, 0),
                     'p1': (-1, 3),
                     'p2': (3, 0),
                     'text': "γ",
                     'text_kw': {'color': 'tab:blue',
                                 'fontsize': 'large'},
                     'size': 1.7,
                     'zorder': 1,
                     'color': 'tab:blue',
                     'facecolor': '#E9F5FD',
                     },
                ],
            },
        ),
    ]
)


umfang_und_flacheninhalt_uben = QuestionSet(
    grade='8',
    capital='Flächen',
    subcapital='Umfang und Flächeninhalt von Kreisen',
    title='Umfang und Flächeninhalt üben',
    instruction='',
    question_type='gap',
    questions=[
        Question(
            instruction='Berechne den Umfang des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>U = 2π * r<br>= 2π * ___ {{units}}<br>≈ ___ {{units}}</mat>',
            correct='{{v1}};{{"%.2f"|format(v1*2*3.14)}}',
            variables={
                'v1': (randdecimal, 2, 5),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (0, 1),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'text': 'r = {{v1}} {{units}}',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'bottom',
                     }},
                ],
                'texts': [
                    {'x': 1.03,
                     'y': 0.97,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'top',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Flächeninhalt des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>A = π * r^2<br>= π(___ {{units}})^2<br>= π * ___ {{units}}^2<br>≈ ___ {{units}}^2</mat>',
            correct='{{v1}};{{"%.2f"|format(v1**2)}};{{"%.2f"|format(3.14*v1**2)}}',
            variables={
                'v1': (randdecimal, 2, 5),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (0, 1),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'text': 'r = {{v1}} {{units}}',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'bottom',
                     }},
                ],
                'texts': [
                    {'x': 1.03,
                     'y': 0.97,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'left',
                     'va': 'top',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>U = 2π * r<br>= 2π * ___ {{units}}<br>≈ ___ {{units}}</mat>',
            correct='{{v1}};{{"%.2f"|format(v1*2*3.14)}}',
            variables={
                'v1': (randint, 20, 50),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (0.293, 0.293),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'text': 'r = {{v1}} {{units}}',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'top',
                         'ha': 'left',
                     }},
                ],
                'texts': [
                    {'x': 0.97,
                     'y': 1.03,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Flächeninhalt des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>A = π * r^2<br>= π(___ {{units}})^2<br>= π * ___ {{units}}^2<br>≈ ___ {{units}}^2</mat>',
            correct='{{v1}};{{v1**2}};{{"%.2f"|format(3.14*v1**2)}}',
            variables={
                'v1': (randint, 20, 50),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (0.293, 0.293),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'text': 'r = {{v1}} {{units}}',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'top',
                         'ha': 'left',
                     }},
                ],
                'texts': [
                    {'x': 0.97,
                     'y': 1.03,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'bottom',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Umfang des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>U = 2π * r<br>= 2π * ___ {{units}}<br>≈ ___ {{units}}</mat>',
            correct='{{v1}};{{"%.2f"|format(v1*2*3.14)}}',
            variables={
                'v1': (randdecimal, 20, 30),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (1.94, 0.658),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     },
                    {'p1': (1, 1),
                     'p2': (1.626, 0.772),
                     'linewidth': 0,
                     'text': 'r = {{v1}} {{units}}',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'bottom',
                         'ha': 'left',
                     }},
                ],
                'texts': [
                    {'x': 0.97,
                     'y': 1,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'center',
                     }
                ]
            },
        ),
        Question(
            instruction='Berechne den Flächeninhalt des Kreises. Runde beides auf zwei Nachkommastellen.',
            formula='<mat>A = π * r^2<br>= π(___ {{units}})^2<br>= π * ___ {{units}}^2<br>≈ ___ {{units}}^2</mat>',
            correct='{{v1}};{{"%.2f"|format(v1**2)}};{{"%.2f"|format(3.14*v1**2)}}',
            variables={
                'v1': (randdecimal, 20, 30),
                'units': (choice, measurement_units),
            },
            image={
                'draw_grid': False,
                'draw_axes': False,
                'axis_limits': {'xmin': '0',
                                'xmax': '2',
                                'ymin': '0',
                                'ymax': '2'},
                'ellipses': [
                    {'xy': (1, 1),
                     'width': 2,
                     'height': 2,
                     'facecolor': 'None',
                     'edgecolor': 'black',
                     'linewidth': 2,
                     },
                ],
                'lines': [
                    {'p1': (1, 1),
                     'p2': (1.94, 0.658),
                     'linewidth': 2,
                     'color': 'tab:blue',
                     'marker': '.',
                     'markevery': [0],
                     'markerfacecolor': 'black',
                     },
                    {'p1': (1, 1),
                     'p2': (1.626, 0.772),
                     'linewidth': 0,
                     'text': 'r = {{v1}} {{units}}',
                     'text_kw': {
                         'rotation': 0,
                         'fontsize': 'large',
                         'color': 'tab:blue',
                         'va': 'bottom',
                         'ha': 'left',
                     }},
                ],
                'texts': [
                    {'x': 0.97,
                     'y': 1,
                     's': 'M',
                     'color': 'black',
                     'fontsize': 'x-large',
                     'ha': 'right',
                     'va': 'center',
                     }
                ]
            },
        ),
    ]
)

question_sets = [
    # satz_des_thales,
    # winkel_berechnen_1_gap,
    # winkel_berechnen_1_mc,
    winkel_berechnen_2,
    umfang_und_flacheninhalt_uben,
]
